// IPC DTO types — re-exported from the shared Zod schema (single source of truth).
// See shared/ipc/schema.ts for the canonical definitions.
export type {
  AppStatus,
  DuplicateGroup,
  DuplicatesResult,
  FileDetail,
  FileRow,
  HistoryEntryRow,
  HistoryPage,
  HistoryQuery,
  Kind,
  PlayEntry,
  ScanDone,
  ScanProgress,
  SceneBookmark,
  SearchCursor,
  SearchQuery,
  SearchResult,
  TagInfo,
  ThumbDone,
  UserCollection,
  UserCollectionItem,
  WorkspaceInfo,
  WorkspaceStats,
  WorkspacesList,
} from "@shared/ipc/schema";
