// IPC DTO types — re-exported from the shared Zod schema (single source of truth).
// See shared/ipc/schema.ts for the canonical definitions.
export type {
  AppStatus,
  DayScope,
  DuplicateGroup,
  DuplicatesResult,
  FileDetail,
  FileRow,
  FolderEntry,
  FolderFilesResult,
  FolderListing,
  FolderPath,
  FolderScope,
  HistoryEntryRow,
  HistoryPage,
  HistoryQuery,
  Kind,
  PlayEntry,
  ScanDone,
  ScanProgress,
  SceneBookmark,
  SearchCursor,
  SearchQuery,
  SearchResult,
  TagInfo,
  TagList,
  TagRef,
  TagSourceCount,
  TagSummary,
  ThumbDone,
  UserCollection,
  UserCollectionItem,
  WorkspaceInfo,
  WorkspaceStats,
  WorkspacesList,
} from "@shared/ipc/schema";
