// Pixel-art frames for the zabuton pet.
//
// Each frame is a PET_WIDTH x PET_HEIGHT text grid, one character per pixel.
// A character names a color role (see PET_SYMBOLS); "." is transparent. The
// grids are rendered to SVG by petRender.ts, which both the app and the
// standalone preview page (tools/pet-preview) use.
//
// The feet rest on the bottom row, so the bottom edge of the canvas is the
// floor line.

export const PET_WIDTH = 24;
export const PET_HEIGHT = 20;

export type PetRole =
  "outline" | "body" | "bodyShade" | "bodyLight" | "stitch" | "tassel" | "face";

/** Grid symbol → color role. "." is transparent and is not listed. */
export const PET_SYMBOLS: Readonly<Record<string, PetRole>> = {
  O: "outline",
  B: "body",
  S: "bodyShade",
  L: "bodyLight",
  T: "stitch",
  G: "tassel",
  F: "face",
};

export type PetFrame = readonly string[];

export interface PetAnimation {
  frames: readonly PetFrame[];
  /** How long each frame stays up. */
  frameMs: number;
  /** Loop until the state changes; otherwise hold the last frame. */
  loop: boolean;
}

export const PET_STATES = [
  "idle",
  "walk",
  "sleep",
  "held",
  "fall",
  "land",
  "hop",
  "mouthOpen",
  "munch",
  "headShake",
  "work",
  "cheer",
  "yum",
  "lookAround",
  "fold",
] as const;

export type PetState = (typeof PET_STATES)[number];

export const PET_ANIMATIONS: Readonly<Record<PetState, PetAnimation>> = {
  // Standing still, breathing and blinking.
  idle: {
    frameMs: 600,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBFBBBBBBFBBSOGGGO",
        "OGOOOLBBFBBBBBBFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBFBBBBBBFBBSOGGGO",
        "OGOOOLBBFBBBBBBFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBBBBBBBBBSOGGGO",
        "OGOOOLBFFBBBBBFFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Wandering along the floor; the feet step in turn.
  walk: {
    frameMs: 160,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".....................OO.",
        ".......OOOOOOOOOO...OGGO",
        "...O.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "OGGOOLBBFBBBBBBFBBSOO...",
        "OGGOLBBBBBBBBBBBBBBSO...",
        ".OOOBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OGOOOOOOOOOO......",
        "......OGO......OGO......",
        ".....OGGGO.....OGO......",
        "......OOO.....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBFBBBBBBFBBSOGGGO",
        "OGOOOLBBFBBBBBBFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".OO.....................",
        "OGGO...OOOOOOOOOO.......",
        "OGGO.OOLLLBBBBBBBOO.O...",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "...OOLBBFBBBBBBFBBSOOGGO",
        "...OLBBBBBBBBBBBBBBSOGGO",
        "...OBBBBBBBFFBBBBBBSOOO.",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOGO......",
        "......OGO......OGO......",
        "......OGO.....OGGGO.....",
        ".....OGGGO.....OOO......",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBFBBBBBBFBBSOGGGO",
        "OGOOOLBBFBBBBBBFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Flattened out asleep after idling for a while.
  sleep: {
    frameMs: 900,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".......OOOOOOOOOO.......",
        "...O.OOLLLBBBBBBBOO.O...",
        ".OOGOLLFFBBBBBFFBBSOGOO.",
        "OGGOOLBBBBBBBBBBBBSOOGGO",
        "OGGOTTBBBBBBBBBBBBTTOGGO",
        ".OOOSBTTTTTTTTTTTTBSOOO.",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        ".......O........O.......",
      ],
      [
        "..................OOO...",
        ".................OTTTO..",
        "..................OTO...",
        ".................OTTTO..",
        "..................OOO...",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".......OOOOOOOOOO.......",
        "...O.OOFFLBBBBFFBOO.O...",
        ".OOGOLLBBBBBBBBBBBSOGOO.",
        "OGGOOTBBBBBBBBBBBBTOOGGO",
        "OGGOSBTTTTTTTTTTTTBSOGGO",
        ".OO.OOSSSSSSSSSSSSOO.OO.",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        ".......O........O.......",
      ],
    ],
  },
  // Lifted by a drag; the feet dangle.
  held: {
    frameMs: 220,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFFBBBBBFFBSOGOO.",
        "...OOLBBFFBBBBBFFBSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        ".....OOGO......OGO......",
        "....OGGO.......OGO......",
        "....OGGO......OGGGO.....",
        ".....OO........OOO......",
        "........................",
      ],
      [
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFFBBBBBFFBSOGOO.",
        "...OOLBBFFBBBBBFFBSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGOO.....",
        "......OGO.......OGGO....",
        ".....OGGGO......OGGO....",
        "......OOO........OO.....",
        "........................",
      ],
    ],
  },
  // Released in mid-air; the tassels flail.
  fall: {
    frameMs: 120,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        ".OO.....................",
        "OGGO...OOOOOOOOOO.....O.",
        "OGGO.OOLLLBBBBBBBOO.OOGO",
        ".OOGOLLFBBBBBBBFBBSOGGGO",
        "...OOLBBFBBBBBFBBBSOOOGO",
        "...OLBBFBBBBBBBFBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        ".....OOGO......OGOO.....",
        "....OGGO........OGGO....",
        "....OGGO........OGGO....",
        ".....OO..........OO.....",
        "........................",
      ],
      [
        "........................",
        "........................",
        "........................",
        ".....................OO.",
        ".O.....OOOOOOOOOO...OGGO",
        "OGOO.OOLLLBBBBBBBOO.OGGO",
        "OGGGOLLFBBBBBBBFBBSOGOO.",
        "OGOOOLBBFBBBBBFBBBSOO...",
        ".O.OLBBFBBBBBBBFBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        ".....OOGO......OGOO.....",
        "....OGGO........OGGO....",
        "....OGGO........OGGO....",
        ".....OO..........OO.....",
        "........................",
      ],
    ],
  },
  // Squash on touching the floor, then rebound.
  land: {
    frameMs: 110,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....FOOOOOOOFO.....O.",
        "OGOO.OOLFLBBBBFBBOO.OOGO",
        "OGGGOLLFBBBBBBBFBBSOGGGO",
        "OGOOOTBBBBBFFBBBBBTOOOGO",
        ".O.OSBTTTTTTTTTTTTBSO.O.",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        ".......O........O.......",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLFLBBBBBFBOO.OOGO",
        "OGGGOLLBFBBBBBBFBBSOGGGO",
        "OGOOOLBBBBBBBBBBBBSOOOGO",
        ".O.OLBBBBBBFFBBBBBBSO.O.",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Click reaction: crouch, then spring up. The jump itself is a transform.
  hop: {
    frameMs: 120,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".......OOOOOOOOOO.......",
        "...O.OOLLLBBBBBBBOO.O...",
        ".OOGOLLFFBBBBBFFBBSOGOO.",
        "OGGOOLBBBBBBBBBBBBSOOGGO",
        "OGGOLBBBBBBFFBBBBBBSOGGO",
        ".OOOTTBBBBBBBBBBBBTTOOO.",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "..OO................OO..",
        ".OGGO...OOOOOOOO...OGGO.",
        ".OGGO.OOLLLBBBBBOO.OGGO.",
        "..OOGOLLBBBBBBBBBSOGOO..",
        "....OOLBBBBBBBBBBSOO....",
        "....OLBBFBBBBBBFBBSO....",
        "....OBBFBFBBBBFBFBSO....",
        "....OBBBBBBBBBBBBBSO....",
        "....OBBBBBBFFBBBBBSO....",
        "....OBBBBBBFFBBBBBSO....",
        "....OBBBBBBBBBBBBBSO....",
        "....OTTBBBBBBBBBBTTO....",
        "....OSBTTTTTTTTTTBSO....",
        ".....OOSSSSSSSSSSOO.....",
        ".......OOOOOOOOOO.......",
        ".......OGO....OGO.......",
        ".......OGO....OGO.......",
        "......OGGGO..OGGGO......",
      ],
    ],
  },
  // A file drag is in progress: looking up with the mouth open.
  mouthOpen: {
    frameMs: 260,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLFLBBBBBFBOO.OGGO",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "...OOLBBBBBBBBBBBBSOO...",
        "...OLBBBBBFFFFBBBBBSO...",
        "...OBBBBBBFSSFBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "...OOLBBFBBBBBBFBBSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBBFFFFBBBBBSO...",
        "...OBBBBBBFSSFBBBBBSO...",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Chewing a dropped file.
  munch: {
    frameMs: 160,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBBBBBBBBBSOGGGO",
        "OGOOOLBFFBBBBBFFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBFFFFBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBBBBBBBBBSOGGGO",
        "OGOOOLBFFBBBBBFFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBBBBBBBBBSOGGGO",
        "OGOOOLBFFBBBBBFFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBFFFFBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Every dropped file was already on Watch Later.
  headShake: {
    frameMs: 140,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOFLBBBBBBFBBBBSOGGGO",
        "OGOOOLFBBBBBFBBBBBSOOOGO",
        ".O.OLFBBBBBBBFBBBBBSO.O.",
        "...OBBBBBFFBBBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLFBBBBBBBFBBSOGGGO",
        "OGOOOLBBFBBBBBFBBBSOOOGO",
        ".O.OLBBFBBBBBBBFBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBFBBBBBBBFSOGGGO",
        "OGOOOLBBBBFBBBBBFBSOOOGO",
        ".O.OLBBBBFBBBBBBBFBSO.O.",
        "...OBBBBBBBBBFFBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // A scan is running: waving the tassels.
  work: {
    frameMs: 220,
    loop: true,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".OO.....................",
        "OGGO...OOOOOOOOOO.......",
        "OGGO.OOLLLBBBBBBBOO.O...",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "...OOLBBFBBBBBBFBBSOOGGO",
        "...OLBBBBBBBBBBBBBBSOGGO",
        "...OBBBBBBBFFBBBBBBSOOO.",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".....................OO.",
        ".......OOOOOOOOOO...OGGO",
        "...O.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "OGGOOLBBFBBBBBBFBBSOO...",
        "OGGOLBBBBBBBBBBBBBBSO...",
        ".OOOBBBBBBBFFBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // A scan finished, or something was brought back.
  cheer: {
    frameMs: 200,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBBBBBBBBBBBSOGOO.",
        "...OOLBBFBBBBBBFBBSOO...",
        "...OLBBFBFBBBBFBFBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OBBBBBBFFFFBBBBBSO...",
        "...OBBBBBBFSSFBBBBBSO...",
        "...OTTBBBBBFFBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
        "......OOO......OOO......",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBFBBBBBBFBBSOGOO.",
        "...OOLBFBFBBBBFBFBSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBBFBBFBBBBBSO...",
        "...OTTBBBBBFFBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // A dropped file was eaten: delighted, with hearts floating up.
  yum: {
    frameMs: 240,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "..............O.O.......",
        ".............OTOTO......",
        ".............OTTTO......",
        "..............OTO.......",
        "...............O........",
        "........................",
        ".......OOOOOOOOOO.......",
        "...O.OOLFLBBBBBFBOO.O...",
        ".OOGOLLFBFBBBBFBFBSOGOO.",
        "OGGOOLBBBBBBBBBBBBSOOGGO",
        "OGGOLBBBBBFBBFBBBBBSOGGO",
        ".OOOTTBBBBBFFBBBBBTTOOO.",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "..............O.O.......",
        ".............OTOTO......",
        "............OTTTTTO.....",
        ".............OTTTO......",
        "..............OTO.......",
        "...............O........",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLFBBBBBBFBBBSOGOO.",
        "...OOLFBFBBBBFBFBBSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBFFFFBBBBBBSO...",
        "...OTTBBBFSSFBBBBBTTO...",
        "...OSBTTTTFFTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "...............O.O......",
        "..............OTOTO.....",
        ".......O.O...OTTTTTO....",
        "......OTOTO...OTTTO.....",
        "......OTTTO....OTO......",
        ".......OTO......O.......",
        "........O...............",
        ".OO.....................",
        "OGGO...OOOOOOOOOO.......",
        "OGGO.OOLFLBBBBBFBOO.O...",
        ".OOGOLLFBFBBBBFBFBSOGOO.",
        "...OOLBBBBBBBBBBBBSOOGGO",
        "...OLBBBBBFBBFBBBBBSOGGO",
        "...OTTBBBBBFFBBBBBTTOOO.",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        ".......O.O..............",
        "......OTOTO....O.O......",
        ".....OTTTTTO..OTOTO.....",
        "......OTTTO...OTTTO.....",
        ".......OTO.....OTO......",
        "........O.......O.......",
        ".OO..................OO.",
        "OGGO...OOOOOOOOOO...OGGO",
        "OGGO.OOLLLBBBBBBBOO.OGGO",
        ".OOGOLLBBFBBBBBBFBSOGOO.",
        "...OOLBBFBFBBBBFBFSOO...",
        "...OLBBBBBBBBBBBBBBSO...",
        "...OBBBBBBBFBBFBBBBSO...",
        "...OTTBBBBBBFFBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // The workspace changed.
  lookAround: {
    frameMs: 450,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLFBBBBBBFBBBBSOGGGO",
        "OGOOOLFBBBBBBFBBBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBFFBBBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBBBBBBBBBSOGGGO",
        "OGOOOLBFFBBBBBFFBBSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBFFBBBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".O.....OOOOOOOOOO.....O.",
        "OGOO.OOLLLBBBBBBBOO.OOGO",
        "OGGGOLLBBBFBBBBBBFSOGGGO",
        "OGOOOLBBBBFBBBBBBFSOOOGO",
        ".O.OLBBBBBBBBBBBBBBSO.O.",
        "...OBBBBBBBBBFFBBBBSO...",
        "...OBBBBBBBBBBBBBBBSO...",
        "...OTTBBBBBBBBBBBBTTO...",
        "...OSBTTTTTTTTTTTTBSO...",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        "......OGO......OGO......",
        ".....OGGGO....OGGGO.....",
      ],
    ],
  },
  // Put away: the cushion folds up before hiding.
  fold: {
    frameMs: 180,
    loop: false,
    frames: [
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".......OOOOOOOOOO.......",
        "...O.OOFLLBBBBBFBOO.O...",
        ".OOGOLLBFBBBBBFBBBSOGOO.",
        "OGGOOLBFBBBBBBBFBBSOOGGO",
        "OGGOTTBBBBBFFBBBBBTTOGGO",
        ".OOOSBTTTTTTTTTTTTBSOOO.",
        "....OOSSSSSSSSSSSSOO....",
        "......OOOOOOOOOOOO......",
        "......OGO......OGO......",
        ".......O........O.......",
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "..........OOOO..........",
        "......O.OOLLLBOO.O......",
        "....OOGFFLBBBBFFOGOO....",
        "...OGGOOLBBBBBBSOOGGO...",
        "...OGGOLBBBBBBBBSOGGO...",
        "....OOOBBBBBBBBBSOOO....",
        "......OSBBBBBBBBSO......",
        ".......OOSSSSSSOO.......",
        ".........OOOOOO.........",
        ".........OGOOGO.........",
        "..........O..O..........",
      ],
    ],
  },
};
