// Compiles the graph view's force simulation (assembly/forces.ts, AssemblyScript)
// to WebAssembly and writes it into src/graph/sim/forcesWasm.ts as base64, so the
// layout worker can instantiate it without fetching a file (the renderer runs
// from file://). Run after changing assembly/forces.ts:
//
//   npm run build:wasm
//
// A renderer test compiles the source again and fails if the committed module
// is out of date.
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import asc from "assemblyscript/asc";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE = path.join(root, "assembly", "forces.ts");
export const OUTPUT = path.join(root, "src", "graph", "sim", "forcesWasm.ts");

/** The WebAssembly binary built from assembly/forces.ts. */
export async function compileForces() {
  let binary = null;
  const errors = [];
  const { error } = await asc.main(
    [
      path.relative(root, SOURCE),
      "--outFile",
      "forces.wasm",
      "-O3",
      "--runtime",
      "stub",
      "--noAssert",
    ],
    {
      readFile: (name, dir) =>
        fs
          .readFile(path.resolve(root, dir ?? "", name), "utf8")
          .catch(() => null),
      writeFile: (name, contents) => {
        if (name.endsWith(".wasm")) binary = contents;
      },
      listFiles: () => [],
      stdout: { write: () => {} },
      stderr: { write: (s) => errors.push(String(s)) },
    },
  );
  if (error || !binary)
    throw new Error(
      `assemblyscript: ${error?.message ?? ""}\n${errors.join("")}`,
    );
  return binary;
}

/** The generated module's text for a binary. */
export function moduleText(binary) {
  return [
    "// Generated by scripts/build-wasm.mjs from assembly/forces.ts. Do not edit:",
    "// run `npm run build:wasm` after changing the source.",
    `export const FORCES_WASM_BASE64 =\n  "${Buffer.from(binary).toString("base64")}";`,
    "",
  ].join("\n");
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const binary = await compileForces();
  await fs.writeFile(OUTPUT, moduleText(binary));
  console.log(
    `wrote ${path.relative(root, OUTPUT)} (${binary.length} bytes of wasm)`,
  );
}
