// Install the built AppImage into the user's local desktop environment.
// Requires `npm run dist` to have produced release/*.AppImage beforehand.

import {
  existsSync,
  readdirSync,
  statSync,
  copyFileSync,
  chmodSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const APP_NAME = "Meguri";
const BIN_NAME = "meguri";
const ICON_NAME = "meguri";
const DESKTOP_FILE = "meguri.desktop";
const URL_HANDLER_NAME = "meguri-open";
const URL_DESKTOP_FILE = "meguri-url.desktop";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const releaseDir = join(projectRoot, "release");
const iconSrc = join(projectRoot, "build", "icon.png");

const home = homedir();
const binDir = join(home, ".local", "bin");
const pixmapDir = join(home, ".local", "share", "pixmaps");
const appsDir = join(home, ".local", "share", "applications");

const binPath = join(binDir, BIN_NAME);
const iconPath = join(pixmapDir, `${ICON_NAME}.png`);
const desktopPath = join(appsDir, DESKTOP_FILE);
const urlHandlerPath = join(binDir, URL_HANDLER_NAME);
const urlDesktopPath = join(appsDir, URL_DESKTOP_FILE);

function archTag() {
  // Map to electron-builder's Linux AppImage suffix (x64 -> x86_64, etc.)
  switch (process.arch) {
    case "x64":
      return "x86_64";
    case "ia32":
      return "i386";
    case "arm":
      return "armv7l";
    default:
      return process.arch;
  }
}

function findLatestAppImage() {
  if (!existsSync(releaseDir)) {
    throw new Error(
      `release/ directory not found. Run \`npm run dist\` first.`,
    );
  }
  const prefix = APP_NAME.toLowerCase();
  const archSuffix = `linux-${archTag()}`;
  const candidates = readdirSync(releaseDir)
    .filter((name) => {
      const lower = name.toLowerCase();
      return (
        lower.endsWith(".appimage") &&
        lower.startsWith(prefix) &&
        lower.includes(archSuffix)
      );
    })
    .map((name) => ({
      full: join(releaseDir, name),
      stat: statSync(join(releaseDir, name)),
    }))
    .filter(({ stat }) => stat.isFile())
    .sort((a, b) => b.stat.mtimeMs - a.stat.mtimeMs);
  if (candidates.length === 0) {
    throw new Error(
      `"${APP_NAME}-*-${archSuffix}.AppImage" not found in release/. Run \`npm run dist\` first.`,
    );
  }
  return candidates[0].full;
}

function isRunning() {
  const r = spawnSync("pgrep", ["-fx", binPath], { stdio: "ignore" });
  return r.status === 0;
}

function buildDesktopEntry() {
  return [
    "[Desktop Entry]",
    "Type=Application",
    `Name=${APP_NAME}`,
    "Comment=Local video and image browser",
    // %U: accepts both file paths and URLs (required for x-scheme-handler).
    `Exec=${binPath} %U`,
    `Icon=${ICON_NAME}`,
    "Terminal=false",
    "Categories=AudioVideo;Video;",
    `StartupWMClass=${APP_NAME}`,
    "",
  ].join("\n");
}

// URL scheme handler. Spawning the AppImage just to relay meguri:// to the
// running instance costs a full Electron boot (~1s); this script instead hits
// the app's control endpoint (published to ~/.config/Meguri/control.json)
// and falls back to launching the app when it isn't running.
function buildUrlHandlerScript() {
  return [
    "#!/usr/bin/env bash",
    "# meguri-open: fast-path handler for meguri:// URLs.",
    "# Generated by scripts/install-local.mjs — do not edit by hand.",
    'ctl="${XDG_CONFIG_HOME:-$HOME/.config}/Meguri/control.json"',
    'if command -v curl >/dev/null 2>&1 && [ -r "$ctl" ]; then',
    '  port=$(sed -n \'s/.*"port":\\([0-9]*\\).*/\\1/p\' "$ctl")',
    '  token=$(sed -n \'s/.*"token":"\\([^"]*\\)".*/\\1/p\' "$ctl")',
    '  if [ -n "$port" ] && [ -n "$token" ] &&',
    '    curl -fsS -m 2 -H "X-Api-Token: $token" \\',
    '      "http://127.0.0.1:$port/show" >/dev/null 2>&1; then',
    "    exit 0",
    "  fi",
    "fi",
    "# Slow path: app not running (or stale control file) — launch it.",
    `exec "${binPath}" "$@"`,
    "",
  ].join("\n");
}

// Separate NoDisplay entry so the scheme handler goes through meguri-open
// while the launcher-visible entry keeps launching the app directly.
function buildUrlDesktopEntry() {
  return [
    "[Desktop Entry]",
    "Type=Application",
    `Name=${APP_NAME} URL Handler`,
    `Exec=${urlHandlerPath} %U`,
    `Icon=${ICON_NAME}`,
    "Terminal=false",
    "NoDisplay=true",
    "MimeType=x-scheme-handler/meguri;",
    "",
  ].join("\n");
}

function main() {
  if (process.platform !== "linux") {
    throw new Error(
      `This script is Linux-only (current: ${process.platform}). On macOS install the dmg, on Windows install the exe directly.`,
    );
  }

  const appImage = findLatestAppImage();
  console.log(`[install] AppImage: ${appImage}`);

  if (isRunning()) {
    console.warn(
      `[install] Warning: ${BIN_NAME} may be running. Overwriting is safe, but a restart is required for the new binary to take effect.`,
    );
  }

  mkdirSync(binDir, { recursive: true });
  copyFileSync(appImage, binPath);
  chmodSync(binPath, 0o755);
  console.log(`[install] Binary: ${binPath}`);

  if (existsSync(iconSrc)) {
    mkdirSync(pixmapDir, { recursive: true });
    copyFileSync(iconSrc, iconPath);
    chmodSync(iconPath, 0o644);
    console.log(`[install] Icon: ${iconPath}`);
  } else {
    console.warn(`[install] build/icon.png not found, skipping icon`);
  }

  writeFileSync(urlHandlerPath, buildUrlHandlerScript());
  chmodSync(urlHandlerPath, 0o755);
  console.log(`[install] URL handler: ${urlHandlerPath}`);

  mkdirSync(appsDir, { recursive: true });
  writeFileSync(desktopPath, buildDesktopEntry());
  chmodSync(desktopPath, 0o644);
  console.log(`[install] .desktop: ${desktopPath}`);

  writeFileSync(urlDesktopPath, buildUrlDesktopEntry());
  chmodSync(urlDesktopPath, 0o644);
  console.log(`[install] .desktop (URL handler): ${urlDesktopPath}`);

  const upd = spawnSync("update-desktop-database", [appsDir], {
    stdio: "inherit",
  });
  if (upd.error) {
    console.warn(
      `[install] update-desktop-database not found (skipping this is usually fine)`,
    );
  }

  // Register as the default handler for meguri:// so xdg-open resolves it.
  const mime = spawnSync(
    "xdg-mime",
    ["default", URL_DESKTOP_FILE, "x-scheme-handler/meguri"],
    { stdio: "inherit" },
  );
  if (mime.error) {
    console.warn(
      `[install] xdg-mime not found; meguri:// URLs may not resolve until registered manually`,
    );
  } else {
    console.log(`[install] URL scheme: meguri:// -> ${URL_DESKTOP_FILE}`);
  }

  console.log(
    `\n[install] Done. You can launch "${APP_NAME}" from the app launcher.`,
  );
  console.log(`[install] From the CLI: ${BIN_NAME}`);

  const pathDirs = (process.env.PATH ?? "").split(":").map((p) => {
    try {
      return resolve(p);
    } catch {
      return p;
    }
  });
  if (!pathDirs.includes(resolve(binDir))) {
    console.log(`[install] Note: if ${binDir} is not on your PATH, add it.`);
  }
}

try {
  main();
} catch (err) {
  console.error(`[install] Error: ${err instanceof Error ? err.message : err}`);
  process.exit(1);
}
